export let keyboardsData = [
  {
    id: 1,
    eng: "1",
    chi: "ㄅ",
    bigEng: "!",
    tMain: {
      text: "ๅ",
      start: 0,
      dur: 0,
      sound: "a:",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "+",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 2,
    eng: "2",
    chi: "ㄉ",
    bigEng: "@",
    tMain: { text: "/", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "๑",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 3,
    eng: "3",
    chi: "ˇ",
    bigEng: "#",
    tMain: { text: "-", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "๒",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 4,
    eng: "4",
    chi: "ˋ",
    bigEng: "$",
    tMain: {
      text: "ภ",
      start: 175,
      dur: 3500,
      sound: "pho sam phao",
      vocabulary: "ภ.สำเภา",
      mean: "帆船",
    },
    tShift: {
      text: "๓",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 5,
    eng: "5",
    chi: "ㄓ",
    bigEng: "%",
    tMain: {
      text: "ถ",
      start: 118,
      dur: 3500,
      sound: "tho thung",
      vocabulary: "ถ.ถุง",
      mean: "袋子",
    },
    tShift: {
      text: "๔",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 6,
    eng: "6",
    chi: "ˊ",
    bigEng: "^",
    tMain: {
      text: "ุ",
      start: 0,
      dur: 0,
      sound: "u",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ู",
      start: 0,
      dur: 0,
      sound: "u:",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 7,
    eng: "7",
    chi: "˙",
    bigEng: "&",
    tMain: {
      text: "ึ",
      start: 0,
      dur: 0,
      sound: "ue",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "฿",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 8,
    eng: "8",
    chi: "ㄚ",
    bigEng: "*",
    tMain: {
      text: "ค",
      start: 18,
      dur: 3500,
      sound: "kho khwai",
      vocabulary: "ค.ควาย",
      mean: "水牛",
    },
    tShift: {
      text: "๕",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 9,
    eng: "9",
    chi: "ㄞ",
    bigEng: "(",
    tMain: {
      text: "ต",
      start: 112,
      dur: 3500,
      sound: "to tao",
      vocabulary: "ต.เต่า",
      mean: "烏龜",
    },
    tShift: {
      text: "๖",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 10,
    eng: "0",
    chi: "ㄢ",
    bigEng: ")",
    tMain: {
      text: "จ",
      start: 38.5,
      dur: 3500,
      sound: "cho chan",
      vocabulary: "จ.จาน",
      mean: "盤子",
    },
    tShift: {
      text: "๗",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 11,
    eng: "-",
    chi: "ㄦ",
    bigEng: "_",
    tMain: {
      text: "ข",
      start: 26,
      dur: 3500,
      sound: "kho khai",
      vocabulary: "ข.ไข่",
      mean: "蛋",
    },
    tShift: {
      text: "๘",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 12,
    eng: "=",
    chi: "",
    bigEng: "+",
    tMain: {
      text: "ช",
      start: 49.5,
      dur: 3500,
      sound: "cho chang",
      vocabulary: "ช.ช้าง",
      mean: "大象",
    },
    tShift: {
      text: "๙",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 13,
    eng: "q",
    chi: "ㄆ",
    bigEng: "Q",
    tMain: { text: "ๆ", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "๐",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 14,
    eng: "w",
    chi: "ㄊ",
    bigEng: "W",
    tMain: {
      text: "ไ",
      start: 0,
      dur: 0,
      sound: "ai",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: '""',
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 15,
    eng: "e",
    chi: "ㄍ",
    bigEng: "E",
    tMain: {
      text: "ำ",
      start: 0,
      dur: 0,
      sound: "am",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ฎ",
      start: 72,
      dur: 3500,
      sound: "do cha da",
      vocabulary: "ฎ.ชฎา",
      mean: "尖頂冠",
    },
  },
  {
    id: 16,
    eng: "r",
    chi: "ㄐ",
    bigEng: "R",
    tMain: {
      text: "พ",
      start: 165,
      dur: 3500,
      sound: "pho phan",
      vocabulary: "พ.พาน",
      mean: "高腳盤",
    },
    tShift: {
      text: "ฑ",
      start: 90,
      dur: 3500,
      sound: "tho mon tho",
      vocabulary: "ฑ.มณโฑ",
      mean: "曼陀（人物名）",
    },
  },
  {
    id: 17,
    eng: "t",
    chi: "ㄔ",
    bigEng: "T",
    tMain: {
      text: "ะ",
      start: 0,
      dur: 0,
      sound: "a",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ธ",
      start: 129,
      dur: 3500,
      sound: "tho thong",
      vocabulary: "ธ.ธง",
      mean: "旗子",
    },
  },
  {
    id: 18,
    eng: "y",
    chi: "ㄗ",
    bigEng: "Y",
    tMain: { text: "ั", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "ํ",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 19,
    eng: "u",
    chi: "ㄧ",
    bigEng: "U",
    tMain: {
      text: "ี",
      start: 0,
      dur: 0,
      sound: "i:",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "๊",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 20,
    eng: "i",
    chi: "ㄛ",
    bigEng: "I",
    tMain: {
      text: "ร",
      start: 193,
      dur: 3500,
      sound: "ro ruea",
      vocabulary: "ร.เรือ",
      mean: "船",
    },
    tShift: {
      text: "ณ",
      start: 101.5,
      dur: 3500,
      sound: "no nen",
      vocabulary: "ณ.เณร",
      mean: "沙彌",
    },
  },
  {
    id: 21,
    eng: "o",
    chi: "ㄟ",
    bigEng: "O",
    tMain: {
      text: "น",
      start: 135,
      dur: 3500,
      sound: "no nu",
      vocabulary: "น.หนู",
      mean: "老鼠",
    },
    tShift: {
      text: "ฯ",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 22,
    eng: "p",
    chi: "ㄣ",
    bigEng: "P",
    tMain: {
      text: "ย",
      start: 187,
      dur: 3500,
      sound: "yo yak",
      vocabulary: "ย.ยักษ์ ",
      mean: "巨人",
    },
    tShift: {
      text: "ญ",
      start: 66,
      dur: 3500,
      sound: "yo ying",
      vocabulary: "ญ.หญิง",
      mean: "女人",
    },
  },
  {
    id: 23,
    eng: "[",
    chi: "[",
    bigEng: "{",
    tMain: {
      text: "บ",
      start: 140,
      dur: 3500,
      sound: "bo bai mai",
      vocabulary: "บ.ใบไม้",
      mean: "葉子",
    },
    tShift: {
      text: "ฐ",
      start: 83,
      dur: 3500,
      sound: "tho than",
      vocabulary: "ฐ.ฐาน",
      mean: "基座",
    },
  },
  {
    id: 24,
    eng: "]",
    chi: "]",
    bigEng: "}",
    tMain: {
      text: "ล",
      start: 198,
      dur: 3500,
      sound: "lo ling",
      vocabulary: "ล.ลิง",
      mean: "猴子",
    },
    tShift: {
      text: ",",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 25,
    eng: "\\",
    chi: "\\",
    bigEng: "|",
    tMain: {
      text: "ฃ",
      start: 13,
      dur: 3500,
      sound: "kho khuat",
      vocabulary: "ฃ.ขวด",
      mean: "瓶子",
    },
    tShift: {
      text: "ฅ",
      start: 23.5,
      dur: 3500,
      sound: "kho khon",
      vocabulary: "ฅ.คน",
      mean: "人",
    },
  },
  {
    id: 26,
    eng: "a",
    chi: "ㄇ",
    bigEng: "A",
    tMain: {
      text: "ฟ",
      start: 170,
      dur: 3500,
      sound: "fo fan",
      vocabulary: "ฟ.ฟัน",
      mean: "牙齒",
    },
    tShift: {
      text: "ฤ",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 27,
    eng: "s",
    chi: "ㄋ",
    bigEng: "S",
    tMain: {
      text: "ห",
      start: 227,
      dur: 3500,
      sound: "ho hip",
      vocabulary: "ห.หีบ",
      mean: "箱子、盒子",
    },
    tShift: {
      text: "ฆ",
      start: 28,
      dur: 3500,
      sound: "kho ra khang",
      vocabulary: "ฆ.ระฆัง",
      mean: "鐘",
    },
  },
  {
    id: 28,
    eng: "d",
    chi: "ㄎ",
    bigEng: "D",
    tMain: {
      text: "ก",
      start: 2,
      dur: 3500,
      sound: "ko khai",
      vocabulary: "ก.ไก่",
      mean: "雞",
    },
    tShift: {
      text: "ฏ",
      start: 78,
      dur: 3500,
      sound: "to pa tak",
      vocabulary: "ฏ.ปฏัก",
      mean: "標槍",
    },
  },
  {
    id: 29,
    eng: "f",
    chi: "ㄑ",
    bigEng: "F",
    tMain: {
      text: "ด",
      start: 107,
      dur: 3500,
      sound: "do dek",
      vocabulary: "ด.เด็ก",
      mean: "小孩",
    },
    tShift: {
      text: "โ",
      start: 0,
      dur: 0,
      sound: "o:",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 30,
    eng: "g",
    chi: "ㄕ",
    bigEng: "G",
    tMain: {
      text: "เ",
      start: 0,
      dur: 0,
      sound: "e:",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ฌ",
      start: 61,
      dur: 3500,
      sound: "cho choe",
      vocabulary: "ฌ.เฌอ",
      mean: "樹木",
    },
  },
  {
    id: 31,
    eng: "h",
    chi: "ㄘ",
    bigEng: "H",
    tMain: { text: "้", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "็",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 32,
    eng: "j",
    chi: "ㄨ",
    bigEng: "J",
    tMain: { text: "่", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "๋",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 33,
    eng: "k",
    chi: "ㄜ",
    bigEng: "K",
    tMain: { text: "า", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "ษ",
      start: 216,
      dur: 3500,
      sound: "so rue si",
      vocabulary: "ษ.ฤๅษี",
      mean: "隱士",
    },
  },
  {
    id: 34,
    eng: "l",
    chi: "ㄠ",
    bigEng: "L",
    tMain: {
      text: "ส",
      start: 222,
      dur: 3500,
      sound: "so suea",
      vocabulary: "ส.เสือ",
      mean: "老虎",
    },
    tShift: {
      text: "ศ",
      start: 210,
      dur: 3500,
      sound: "so sa la",
      vocabulary: "ศ.ศาลา",
      mean: "涼亭",
    },
  },
  {
    id: 35,
    eng: ";",
    chi: "ㄤ",
    bigEng: ":",
    tMain: {
      text: "ว",
      start: 205,
      dur: 3500,
      sound: "wo waen",
      vocabulary: "ว.แหวน",
      mean: "戒指",
    },
    tShift: {
      text: "ซ",
      start: 55,
      dur: 3500,
      sound: "so so",
      vocabulary: "ซ.โซ่",
      mean: "鎖鏈",
    },
  },
  {
    id: 36,
    eng: "'",
    chi: ",",
    bigEng: '"',
    tMain: {
      text: "ง",
      start: 32,
      dur: 3500,
      sound: "ngo ngu",
      vocabulary: "ง.งู",
      mean: "蛇",
    },
    tShift: {
      text: ".",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 37,
    eng: "z",
    chi: "ㄈ",
    bigEng: "Z",
    tMain: {
      text: "ผ",
      start: 153,
      dur: 3500,
      sound: "pho phueng",
      vocabulary: "ผ.ผึ้ง",
      mean: "蜜蜂",
    },
    tShift: {
      text: "(",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 38,
    eng: "x",
    chi: "ㄌ",
    bigEng: "X",
    tMain: {
      text: "ป",
      start: 147,
      dur: 3500,
      sound: "po pla",
      vocabulary: "ป.ปลา",
      mean: "魚",
    },
    tShift: {
      text: ")",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 39,
    eng: "c",
    chi: "ㄏ",
    bigEng: "C",
    tMain: {
      text: "แ",
      start: 0,
      dur: 0,
      sound: "ae",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ฉ",
      start: 43,
      dur: 3500,
      sound: "cho ching",
      vocabulary: "ฉ.ฉิ่ง",
      mean: "小鈸",
    },
  },
  {
    id: 40,
    eng: "v",
    chi: "ㄒ",
    bigEng: "V",
    tMain: {
      text: "อ",
      start: 239,
      dur: 3500,
      sound: "o ang",
      vocabulary: "อ.อ่าง",
      mean: "盆",
    },
    tShift: {
      text: "ฮ",
      start: 244.5,
      dur: 3500,
      sound: "ho nok huk",
      vocabulary: "ฮ.นกฮูกเจ้าขา",
      mean: "貓頭鷹",
    },
  },
  {
    id: 41,
    eng: "b",
    chi: "ㄖ",
    bigEng: "B",
    tMain: { text: "ิ", start: 0, dur: 0, sound: "", vocabulary: "", mean: "" },
    tShift: {
      text: "ฺ",
      start: 0,
      dur: 0,
      sound: "i",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 42,
    eng: "n",
    chi: "ㄙ",
    bigEng: "N",
    tMain: {
      text: "ื",
      start: 0,
      dur: 0,
      sound: "uu:",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "์",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 43,
    eng: "m",
    chi: "ㄩ",
    bigEng: "M",
    tMain: {
      text: "ท",
      start: 124,
      dur: 3500,
      sound: "tho thahan",
      vocabulary: "ท.ทหาร",
      mean: "軍人",
    },
    tShift: {
      text: "?",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
  {
    id: 44,
    eng: ",",
    chi: "ㄝ",
    bigEng: "<",
    tMain: {
      text: "ม",
      start: 180,
      dur: 3500,
      sound: "mo ma",
      vocabulary: "ม.ม้า",
      mean: "馬",
    },
    tShift: {
      text: "ฒ",
      start: 95,
      dur: 3500,
      sound: "tho pua tao",
      vocabulary: "ฒ.ผู้เฒ่า",
      mean: "老年",
    },
  },
  {
    id: 45,
    eng: ".",
    chi: "ㄡ",
    bigEng: ">",
    tMain: {
      text: "ใ",
      start: 0,
      dur: 0,
      sound: "ai",
      vocabulary: "",
      mean: "",
    },
    tShift: {
      text: "ฬ",
      start: 233,
      dur: 3500,
      sound: "lo chu la",
      vocabulary: "ฬ.จุฬา",
      mean: "風箏",
    },
  },
  {
    id: 46,
    eng: "/",
    chi: "ㄥ",
    bigEng: "?",
    tMain: {
      text: "ฝ",
      start: 158,
      dur: 3500,
      sound: "fo fa",
      vocabulary: "ฝ.ฝา",
      mean: "蓋子",
    },
    tShift: {
      text: "ฦ",
      start: 0,
      dur: 0,
      sound: "",
      vocabulary: "",
      mean: "",
    },
  },
];
